### ISSUE TITLE
Improve link visibility in notification area

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/theme#144]
![screen shot on 2016-11-17 at 16-19-11](https://cloud.githubusercontent.com/assets/4752949/20394980/aba9dee6-ace1-11e6-8fa6-57ee3e316d09.png)

**Comment by michaelbeil** [comment]
We can do the following:
```css
#notification-area a {
    color: #fff;
    border-bottom: 1px dotted #eee;
}
 
#notification-area a:hover {
    color: #fff;
    border-bottom: 1px solid #fff;
}
```

But that adds the border bottom to the SVG for closing the notice:
![screen shot 2016-11-17 at 4 26 41 pm](https://cloud.githubusercontent.com/assets/4752949/20395289/a700c6ec-ace2-11e6-9f82-1619f06b8499.png)
